### ISSUE TITLE
Anyone tried it with NodeMcu and ST7789?

### ISSUE THREAD

**Issue by mwedmark** [corax89/esp8266_game_engine#6]
I've tried this in a ST7789 screen (240x240 pixels) and used my already configured and working TFT_eSPI library I had installed. Compilation is OK and I already downloaded the 27 files using the ESP8266 Upload tool.

Screen goes Black but nothing is shown. 
This is the output in the serial Log:

```
ESPboy
Flash ide speed: 40000000 Hz
Flash ide mode:  DIO
SPIFFS Initialize....ok
FreeHeap:9608
print "vW H" for change viewport, "d name" for delite file,
"s name" for save file and "m" for load to memory
find 27 files
```

What to do next? It would be cool to be able to try this game engine out

**Comment by corax89** [comment]
Change the settings.h file
Lines
#define ESPBOY 1
#define SCREEN_REAL_WIDTH 320
#define SCREEN_REAL_HEIGHT 240
on
#define ESPBOY 0
#define SCREEN_REAL_WIDTH 240
#define SCREEN_REAL_HEIGHT 240

**Comment by mwedmark** [comment]
Thanks for answer!
OK tried that. SCREEN_REAL_WIDTH already changed and nowI  also changed ESPBOY to 0
Still no luck. What should be done? I've tried for example:
m linebench.bin

and other files. Feedback is:
```
FreeHeap:9384
print "vW H" for change viewport, "d name" for delite file,
"s name" for save file and "m" for load to memory
find 27 files
m linebench.load 
0 byte
free heap 9208
bin

```
Is that right and then what?

**Comment by corax89** [comment]
The m command loads HEX into memory. For example, m $90,$00,$0C,$00,$01,$01,$1A,$00,$D1,$11,$9A,$00,$01,$0F,$00,$00,$06,$F0,$26,$00,$99,$00,$04,$00,$50,$00,$68,$65,$6C,$6C,$6F,$20,$77,$6F,$72,$6C,$64,$00.
HEX can be obtained  [here](https://corax89.github.io/esp8266Game/index.html) in the memory field
